import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:equatable/equatable.dart';
import '../../../../domain/entities/workout_set.dart';
import '../../../../domain/usecases/workout_sets/add_workout_set.dart';
import '../../../../domain/usecases/workout_sets/get_weekly_sets.dart';
import '../../../../domain/usecases/muscle_stimulus/record_workout_set.dart';

// ==================== EVENTS ====================

abstract class WorkoutEvent extends Equatable {
  const WorkoutEvent();
  
  @override
  List<Object?> get props => [];
}

/// Event to log a new workout set with muscle stimulus tracking
class LogWorkoutSetEvent extends WorkoutEvent {
  final String exerciseId;
  final int reps;
  final double weight;
  final int intensity; // NEW: Intensity level (0-5)
  final DateTime? date;
  
  const LogWorkoutSetEvent({
    required this.exerciseId,
    required this.reps,
    required this.weight,
    required this.intensity,
    this.date,
  });
  
  @override
  List<Object?> get props => [exerciseId, reps, weight, intensity, date];
}

/// Event to load weekly sets for display
class LoadWeeklySetsEvent extends WorkoutEvent {
  const LoadWeeklySetsEvent();
}

// ==================== STATES ====================

abstract class WorkoutState extends Equatable {
  const WorkoutState();
  
  @override
  List<Object?> get props => [];
}

/// Initial state
class WorkoutInitial extends WorkoutState {}

/// Loading state
class WorkoutLoading extends WorkoutState {}

/// State with loaded weekly sets
class WorkoutDataLoaded extends WorkoutState {
  final List<WorkoutSet> weeklySets;
  
  const WorkoutDataLoaded({
    required this.weeklySets,
  });
  
  @override
  List<Object?> get props => [weeklySets];
}

/// Success state after logging a set
class WorkoutOperationSuccess extends WorkoutState {
  final String message;
  final List<String> affectedMuscles; // NEW: Muscles that received stimulus
  
  const WorkoutOperationSuccess({
    required this.message,
    this.affectedMuscles = const [],
  });
  
  @override
  List<Object?> get props => [message, affectedMuscles];
}

/// Error state
class WorkoutError extends WorkoutState {
  final String message;
  
  const WorkoutError(this.message);
  
  @override
  List<Object?> get props => [message];
}

// ==================== BLOC ====================

/// BLoC for managing workout set logging with muscle stimulus integration
/// 
/// Handles:
/// - Logging workout sets to database
/// - Recording muscle stimulus for affected muscles
/// - Loading weekly sets for progress display
/// - Providing feedback on affected muscles
class WorkoutBloc extends Bloc<WorkoutEvent, WorkoutState> {
  final AddWorkoutSet addWorkoutSet;
  final GetWeeklySets getWeeklySets;
  final RecordWorkoutSet recordWorkoutSet; // NEW: Stimulus recording
  
  WorkoutBloc({
    required this.addWorkoutSet,
    required this.getWeeklySets,
    required this.recordWorkoutSet,
  }) : super(WorkoutInitial()) {
    on<LogWorkoutSetEvent>(_onLogWorkoutSet);
    on<LoadWeeklySetsEvent>(_onLoadWeeklySets);
  }
  
  /// Log a workout set and record muscle stimulus
  Future<void> _onLogWorkoutSet(
    LogWorkoutSetEvent event,
    Emitter<WorkoutState> emit,
  ) async {
    emit(WorkoutLoading());
    
    // Step 1: Add workout set to database
    final workoutSet = WorkoutSet(
      id: '', // Will be generated by use case
      exerciseId: event.exerciseId,
      reps: event.reps,
      weight: event.weight,
      intensity: event.intensity, // NEW: Include intensity
      date: event.date ?? DateTime.now(),
      createdAt: DateTime.now(),
    );
    
    final addSetResult = await addWorkoutSet(workoutSet);
    
    await addSetResult.fold(
      // Error adding workout set
      (failure) async {
        emit(WorkoutError(failure.message));
      },
      // Success - now record muscle stimulus
      (_) async {
        // Step 2: Record muscle stimulus for this set
        final stimulusResult = await recordWorkoutSet(
          exerciseId: event.exerciseId,
          sets: 1, // Single set
          intensity: event.intensity,
          timestamp: event.date,
        );
        
        stimulusResult.fold(
          // Error recording stimulus (non-critical - workout is saved)
          (failure) {
            // Still show success since workout was saved
            emit(const WorkoutOperationSuccess(
              message: 'Set logged successfully (stimulus tracking unavailable)',
              affectedMuscles: [],
            ));
          },
          // Success - show affected muscles
          (affectedMuscles) {
            final muscleList = affectedMuscles.isEmpty 
                ? 'Set logged successfully'
                : 'Set logged! Affected: ${affectedMuscles.join(', ')}';
            
            emit(WorkoutOperationSuccess(
              message: muscleList,
              affectedMuscles: affectedMuscles,
            ));
          },
        );
      },
    );
  }
  
  /// Load weekly sets for display
  Future<void> _onLoadWeeklySets(
    LoadWeeklySetsEvent event,
    Emitter<WorkoutState> emit,
  ) async {
    final setsResult = await getWeeklySets();
    
    setsResult.fold(
      (failure) => emit(WorkoutError(failure.message)),
      (sets) => emit(WorkoutDataLoaded(weeklySets: sets)),
    );
  }
}