include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
  errors:
    todo: ignore

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_empty_else: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    curly_braces_in_flow_control_structures: true
    depend_on_referenced_packages: true
    directives_ordering: true
    join_return_with_assignment: true
    no_adjacent_strings_in_list: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_expression_function_bodies: false
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    use_key_in_widget_constructors: true