name: fitness_tracker
description: A personal fitness tracking app to monitor weekly muscle group training goals.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3          # For state management (BLoC pattern)
  equatable: ^2.0.5             # For value equality in entities/models

  # Database
  sqflite: ^2.3.0              # SQLite database for local storage
  path: ^1.8.3                 # For database path management

  # Date/Time Utilities
  intl: ^0.18.1                # For date formatting and internationalization
  
  # Dependency Injection
  get_it: ^7.6.4               # Service locator for dependency injection
  
  # JSON Serialization
  json_annotation: ^4.8.1      # Annotations for JSON serialization
  
  # UI Components
  cupertino_icons: ^1.0.6      # iOS style icons
  
  # Utils
  uuid: ^4.1.0                 # For generating unique IDs

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7         # For running code generators
  json_serializable: ^6.7.1    # For generating JSON serialization code
  
  # Linting
  flutter_lints: ^3.0.0        # Recommended lints for Flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/data/

  # Custom fonts (optional - uncomment if you add custom fonts)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700