name: fitness_tracker
description: A personal fitness tracking app to monitor weekly muscle group training goals.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # Functional Programming
  dartz: ^0.10.1

  # Date/Time Utilities
  intl: ^0.20.2
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Utils (not using json_serializable, manual serialization instead)
  
  # UI Components
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  
  # Utils
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.8.0
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/data/